-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 00:38:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema banking_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banking_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banking_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
USE `banking_system` ;

-- -----------------------------------------------------
-- Table `banking_system`.`branches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`branches` (
  `branchID` INT NOT NULL,
  `City` VARCHAR(120) NULL DEFAULT NULL,
  `Town` VARCHAR(45) NULL DEFAULT NULL,
  `ContactNumber` INT NULL DEFAULT NULL,
  `BranchBalance` INT NOT NULL,
  PRIMARY KEY (`branchID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`account` (
  `AccountID` INT NOT NULL DEFAULT '0',
  `Balance` INT NULL DEFAULT NULL,
  `OpenDate` DATE NULL DEFAULT NULL,
  `Status` ENUM('active', 'inactive') NULL DEFAULT NULL,
  `AccountPin` INT NOT NULL,
  `branches_branchID` INT NOT NULL,
  PRIMARY KEY (`AccountID`),
  INDEX `fk_account_branches1_idx` (`branches_branchID` ASC) VISIBLE,
  CONSTRAINT `fk_account_branches1`
    FOREIGN KEY (`branches_branchID`)
    REFERENCES `banking_system`.`branches` (`branchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `banking_system`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`auth_group_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `banking_system`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `banking_system`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`auth_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`auth_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`auth_user_groups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `banking_system`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `banking_system`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`auth_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`auth_user_user_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `banking_system`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `banking_system`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`customer` (
  `CustomerID` INT NOT NULL,
  `First_Name` VARCHAR(60) NOT NULL,
  `Last_name` VARCHAR(45) NULL DEFAULT NULL,
  `City` VARCHAR(100) NOT NULL,
  `Town` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(45) NULL DEFAULT NULL,
  `DateOfBirth` DATE NOT NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`customeremails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`customeremails` (
  `EmailID` INT NULL DEFAULT NULL,
  `customer_CustomerID` INT NOT NULL,
  INDEX `fk_CustomerEmails_customer1_idx` (`customer_CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_CustomerEmails_customer1`
    FOREIGN KEY (`customer_CustomerID`)
    REFERENCES `banking_system`.`customer` (`CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`customerphonenumber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`customerphonenumber` (
  `ContactNumber` INT NOT NULL,
  `customer_CustomerID` INT NOT NULL,
  INDEX `fk_CustomerPhoneNumber_customer1_idx` (`customer_CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_CustomerPhoneNumber_customer1`
    FOREIGN KEY (`customer_CustomerID`)
    REFERENCES `banking_system`.`customer` (`CustomerID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `banking_system`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `banking_system`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`django_migrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`employee` (
  `emlpoyeeID` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Last_Name` VARCHAR(45) NULL DEFAULT NULL,
  `Position` ENUM('manager', 'teller') NULL DEFAULT NULL,
  `ContactNumber` INT NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `branches_branchID` INT NOT NULL,
  PRIMARY KEY (`emlpoyeeID`),
  INDEX `fk_employee_branches1_idx` (`branches_branchID` ASC) VISIBLE,
  CONSTRAINT `fk_employee_branches1`
    FOREIGN KEY (`branches_branchID`)
    REFERENCES `banking_system`.`branches` (`branchID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`loan_applications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`loan_applications` (
  `application_id` INT NOT NULL,
  `Amount` INT NULL DEFAULT NULL,
  `DateApplied` DATE NULL DEFAULT NULL,
  `account_AccountID` INT NOT NULL,
  PRIMARY KEY (`application_id`),
  INDEX `fk_loan_applications_account1_idx` (`account_AccountID` ASC) VISIBLE,
  CONSTRAINT `fk_loan_applications_account1`
    FOREIGN KEY (`account_AccountID`)
    REFERENCES `banking_system`.`account` (`AccountID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`loans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`loans` (
  `loanID` INT NOT NULL,
  `Amount` DOUBLE NULL DEFAULT NULL,
  `InterestRate` DOUBLE NULL DEFAULT NULL,
  `DateApproved` DATE NULL DEFAULT NULL,
  `account_AccountID` INT NOT NULL,
  `PaymentStatus` ENUM('paid', 'unpaid') NULL DEFAULT NULL,
  PRIMARY KEY (`loanID`),
  INDEX `fk_loans_account1_idx` (`account_AccountID` ASC) VISIBLE,
  CONSTRAINT `fk_loans_account1`
    FOREIGN KEY (`account_AccountID`)
    REFERENCES `banking_system`.`account` (`AccountID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`loan_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`loan_payment` (
  `Amount` INT NOT NULL,
  `DatePaid` DATE NOT NULL,
  `loans_loanID` INT NOT NULL,
  INDEX `fk_loan_payment_loans1_idx` (`loans_loanID` ASC) VISIBLE,
  CONSTRAINT `fk_loan_payment_loans1`
    FOREIGN KEY (`loans_loanID`)
    REFERENCES `banking_system`.`loans` (`loanID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`transaction` (
  `transactionID` INT NOT NULL,
  `account_AccountID` INT NOT NULL,
  `Amount` DOUBLE NULL DEFAULT NULL,
  `Time` TIME NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `Type` ENUM('loan', 'account To account') NULL DEFAULT NULL,
  `RecipientID` INT NULL DEFAULT NULL,
  `Location` VARCHAR(45) NULL DEFAULT NULL,
  `Purpose` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`transactionID`),
  INDEX `fk_transaction_account1_idx` (`account_AccountID` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_account1`
    FOREIGN KEY (`account_AccountID`)
    REFERENCES `banking_system`.`account` (`AccountID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `banking_system`.`auth_user_has_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banking_system`.`auth_user_has_account` (
  `auth_user_id` INT NOT NULL,
  `account_AccountID` INT NOT NULL,
  PRIMARY KEY (`auth_user_id`, `account_AccountID`),
  INDEX `fk_auth_user_has_account_account1_idx` (`account_AccountID` ASC) VISIBLE,
  INDEX `fk_auth_user_has_account_auth_user1_idx` (`auth_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_auth_user_has_account_auth_user1`
    FOREIGN KEY (`auth_user_id`)
    REFERENCES `banking_system`.`auth_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_user_has_account_account1`
    FOREIGN KEY (`account_AccountID`)
    REFERENCES `banking_system`.`account` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
